### ISSUE TITLE
Git Tags and Tarballs

### ISSUE THREAD

**Issue by ColinKinloch** [dolphin-emu/sadm#158]
I'm trying to automate beta releases for the [flathub build](https://github.com/flathub/org.DolphinEmu.dolphin-emu).
Currently it downloads a specified commit from the dolphin git repo that's updated manually whenever there's a new blog post.
The tool to automate this process, [flatpak-external-data-checker](https://github.com/flathub/flatpak-external-data-checker/), requires either a branch or tag to update the commit.

I've tried pulling the commit hash from `https://dolphin-emu.org/update/latest/beta` and downloading the source from `https://github.com/dolphin-emu/dolphin/archive/{commit}.zip` but as the repo uses submodules this fails to build.

Would it be possible to get any one of these:
* A tag per release: `5.0-16793`
* A branch that follows beta releases: `beta`
* A tarball (or 7z) artefact that includes submodules ([this function](https://github.com/dolphin-emu/sadm/blob/bc1e9a7a7da699fc6d7d37e42c20088ba3c03f62/buildbot/master.cfg#L150-L277) but without the build step)

**Comment by delroth** [comment]
Carrying over the discussion from #160 here: distributing our own source tarballs is a no-go for us -- we could technically do it for beta only, but I'm very much against duplicating data that we already have in our git repo.

Ultimately I think that the root cause here is that your auto-updater infra for Flathub is too restrictive and should support commit hashes instead of only branch/tags. Auto-updating infra for other distros supports this fine, see e.g. [the auto-updater for Dolphin in nixpkgs](https://github.com/NixOS/nixpkgs/blob/master/pkgs/applications/emulators/dolphin-emu/master.nix#L68). You should file a feature request upstream.

We do have long term plans to switch to a new model for "beta", basically deprecating our existing stable builds, switching to a vYY.MM[.r] release naming (e.g. v22.07), and properly tagging those in our repository. The biggest blocker right now for having tags is that we haven't really decided on the details of the release naming -- if we have this decision done then we could start tagging right away even if the rest of our infra doesn't use the tags just yet. Currently I don't have the time to drive the discussions and/or the implementation for this, possibly later in the year.

**Comment by ColinKinloch** [comment]
Extremely embarrassingly I just solved the issue. Forget I said anything.

**Comment by delroth** [comment]
Happy to hear it :)

**Comment by ColinKinloch** [comment]
I tried a few things to get it automated before I found `https://dolphin-emu.org/update/latest/beta`. I just needed to point the commit at the hash field. :flushed:
