### ISSUE TITLE
Remove *-steam-* builders ?

### ISSUE THREAD

**Issue by shuffle2** [dolphin-emu/sadm#180]
Is this builder really helpful? 
AFAIK The only differences from normal build are that AUTOUPDATE is not defined and STEAM is defined.
STEAM macro is never used in the source code (appears to only be used in some cmake stuff). Probably this should be reworked and not exposed as a macro, anyway.

cc @OatmealDome

**Comment by delroth** [comment]
For now there isn't much difference, but we definitely expect more in the future as we start integrating with stuff like steamworks. I'll let OatmealDome give a more authoritative answer though.

**Comment by OatmealDome** [comment]
I'd like to keep this builder if possible.

> Does it actually need a different build tho? Hopefully it can be runtime-dynamic and not a build configuration.

My plan for Steamworks integration involves creating a separate executable that powers the integrations for us. We can't integrate it directly because linking with the SDK would cause a GPL violation. (Similar solutions include [icculus's steamshim](https://github.com/icculus/steamshim) and [RetroArch's mist](https://github.com/libretro/mist/).) This executable shouldn't be built and included on the normal builds, so I was hoping I could lock it behind the `Steam` msbuild property.

> Is this builder really helpful?

Because I don't primarily develop on Windows, I was going to use `pr-steam-win-x64` to make sure those future PRs build properly.

**Comment by OatmealDome** [comment]
Wouldn't Dolphin linking to a `SteamStuff.dll` which links to the Steamworks SDK also cause a GPL violation?

**Comment by Zopolis4** [comment]
Is there a problem having these builders? Like if they were causing a space issue or something sure, but as it stands I don't see any actual issue with them. And if they cause no issue but will lead to a cleaner experience for the end user (not having an unnecessary executable), then why not keep them?

**Comment by Zopolis4** [comment]
We could probably find a compromise by building the steam stuff, then not shipping it for non-steam builds, so having one builder that provides 2 outputs.

**Comment by Zopolis4** [comment]
Or if space is a concern, we could do some fancy thing which strips the steam stuff out on demand.

**Comment by Zopolis4** [comment]
First one would deal with time, second one would probably be good long term. Just because we have the resources to burn doesnt mean we should burn them :p

**Comment by delroth** [comment]
There's nothing being "burned", idle build workers cost us the same as busy build workers. IMO the only argument we should look at is whether compile-time vs runtime gated Steam integration is better, what that means for Buildbot usage bears very little importance.

**Comment by delroth** [comment]
FWIW I don't have a strong opinion either way at this point, assigning to OatmealDome to figure out the long term plan here on how Steam should be handled, feel free to discuss that together and let me know in the end if you keep or don't keep a separate build configuration for this.

**Comment by OatmealDome** [comment]
All builders removed.
